export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'SEARCH_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'SEARCH_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'SEARCH_ROBOTS_FAILED';